services:
  # Frontend Next.js service
  - type: web
    name: frontend
    env: node
    buildCommand: cd frontend && npm install && npm run build
    startCommand: cd frontend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: BACKEND_URL
        fromService:
          name: backend
          type: web
          property: url
    autoDeploy: true
    branch: main
    rootDir: frontend

  # Backend Node.js service  
  - type: web
    name: backend
    env: node
    buildCommand: cd backend && npm install && npm run build
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
    autoDeploy: true
    branch: main
    rootDir: backend