services:
  # Frontend Next.js service
  - type: web
    name: frontend
    env: node
    buildCommand: cd frontend && npm install && npm run build
    startCommand: cd frontend && npm start
    
    autoDeploy: true
    branch: main
    rootDir: frontend

  # Backend Node.js service  
  - type: web
    name: backend
    env: node
    buildCommand: cd backend && npm install && npm run build
    startCommand: cd backend && npm start
    
    autoDeploy: true
    branch: main
    rootDir: backend